default: &default
  adapter: mysql2
  encoding: utf8
  host: 127.0.0.1
  pool: 5
  port: 3306
  username: root

development:
  <<: *default
  database: qchan-api_development

test:
  <<: *default
  database: qchan-api_test

production:
  <<: *default
  database: qchan-api_production
