default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["DATABASE_HOST"] || "127.0.0.1" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "" %>
  pool: 5
  port: <%= ENV["DATABASE_PORT"] || "3306" %>
  username: root

development:
  <<: *default
  database: qchan-api_development

test:
  <<: *default
  database: qchan-api_test

production:
  <<: *default
  database: qchan-api_production
