defaults: &defaults
  github_user_url: "https://api.github.com/user"
  github_authorize_url: "https://github.com/login/authorize"
  github_exchange_url: "https://github.com/login/oauth/access_token"
  github_scope: "public,user"
  github_client_id: <%= ENV["GITHUB_CLIENT_ID"] %>
  github_client_secret: <%= ENV["GITHUB_CLIENT_SECRET"] %>
  redis_host: <%= ENV["REDIS_HOST"] || "localhost" %>
  redis_port: <%= ENV["REDIS_PORT"] || "6379" %>

development:
  <<: *defaults

test:
  <<: *defaults
  github_client_id: "test_client_id"
  github_client_secret: "test_client_secret"

production:
  <<: *defaults
