defaults: &defaults
  github_user_url: "https://api.github.com/user"
  github_authorize_url: "https://github.com/login/authorize"
  github_exchange_url: "https://github.com/login/oauth/access_token"
  github_client_id: "test_client_id"
  github_client_secret: "test_client_secret"
  github_scope: "public,user"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
